name: trip_tracking
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  logger: ^2.0.2+1

  # state
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  provider: ^6.0.5

  # service
  dio: ^4.0.6
  
  bloc_concurrency: ^0.2.0
  stream_transform: ^2.0.0
  
  # desing
  date_picker_timeline: ^1.2.5
  timelines: ^0.1.0

  # cache
  cached_network_image: ^3.2.1
  
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # analysis
  very_good_analysis: ^5.1.0

  # generator
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/
